package com.steave.enums;

public enum ConfigProperties{
    URL,
    OVERRIDEREPORTS,
    PASSEDSTEPSCREENSHOT,
    FAILEDSTEPSCREENSHOT,
    RETRYCOUNT,
    RETRYFAILEDTESTS,
    SKIPPEDSTEPSCREENSHOT,
    RUNREMOTE;
}
